### ISSUE TITLE
V4 or V5

### ISSUE THREAD

**Issue by ne2d** [Salamek/zasilkovna#28] opened 2023-02-09 09:50 UTC
https://github.com/Salamek/zasilkovna/blob/a76f5121173abbb59ba900daa9164bceff803394/src/Branch.php#L29

would it be possible to upgrade to a newer version?

**Comment by Salamek** [comment] 2023-02-09 16:27
I'm sorry but i'm not using this library in any of my maintained/active projects so i have no drive to refactor it...
I'll will maintain this project in my free time just fine (Fix bugs, accept PRs, CO.) but i will not waste hours of work on it while i get nothing in return... also i have no way to test my changes since i have no account on zasilkovna.cz... So there are two options:

a) You can implement & test it your self and send a PR so i can merge those changes
b) You can "donate" $ to support this project in amount that will cover my time refactoring...

**Comment by Salamek** [comment] 2023-02-09 16:29
~Duplicate of #22

**Comment by ne2d** [comment] 2023-02-19 13:15
Branch.php

    $this->jsonEndpoint = 'https://www.zasilkovna.cz/api/v4/' . $apiKey . '/branch.json';

ZasilkovnaBranch.php

    private ?array $directionsCar;
    private ?array $directionsPublic;
    ...
    $this->directionsCar = (array) $data['directionsCar'] ?? [];
    $this->directionsPublic = (array) $data['directionsPublic'] ?? [];

This is my upgrade to V4. Please check it before merge.

**Comment by Salamek** [comment] 2023-02-19 23:42
Does that really return an array? 
Response example at https://docs.packetery.com/01-pickup-point-selection/04-branch-export-v4.html shows it as a string... that official example is wrong i guess?

**Comment by ne2d** [comment] 2023-02-20 07:17
that's weird. I'm dive into data and see ... `"directionsCar":"<p>Parkovisko dostupn\u00e9 v bl\u00edzkosti pobo\u010dky.<\/p>","directionsPublic":[],` and `"directionsCar":[],"directionsPublic":[]`

**Comment by Salamek** [comment] 2023-02-21 13:13
Soo umm... set is string and empty is empty array?  looks like same type that we convert using `Tools::convertToString` function to enforce string... so i think we should keep string type and just change:

https://github.com/Salamek/zasilkovna/blob/9f0bdb4e874910f5d111bf74104ef5ccfe56e42e/src/Entity/ZasilkovnaBranch.php#L80-L81

to:

```php
$this->directionsCar = Tools::convertToString($data['directionsCar']);
$this->directionsPublic = Tools::convertToString($data['directionsPublic']);
```

???

**Comment by ne2d** [comment] 2023-02-21 20:47
Yep we can try it. Please add also $this->directions, in some case it's array

**Comment by Salamek** [comment] 2023-02-21 21:28
Changes are in master, check if it works for you (in composer.json use `dev-master` as version) and let me know... then i do proper release

**Comment by ne2d** [comment] 2023-03-02 14:50
looks good for me

**Comment by Salamek** [comment] 2023-03-02 22:07
Should be part of version 3.1.4

**Closed as completed by Salamek** 2023-03-02 22:07 UTC
Labels: duplicate, enhancement, question
